firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('videos/',include(('video.urls','video'),namespace='video')),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('blog1/',include(('blog1.urls','blog1'),namespace='blog1')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
from django.views.generic import TemplateView

app_name='home'

urlpatterns=[
    path('',views.home, name='home'),
    path("about/",views.about,name='about'),
    path("search/",views.search,name='search'),
]

users/urls.py
from django.urls import path
from users import views




app_name='users'
urlpatterns=[
    path('register',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

video/urls.py
from django.urls import path
from video import views
# from video.views import categories,categoryviews,article_detail


app_name='video'
urlpatterns=[
    path('categorylist/',views.category_list,name='category'),
    path('<slug:category_slug>/',views.category_view,name='category_view'),
    path('postComment',views.postComment, name='postComment'),
    path('<slug:article_slug>',views.article_detail, name='article_detail'),
    #path('slug:category_slug>/',ArticleDetail.as_view(),name='article_detail'),
    #path('slug:category_slug>/',categoryviews.as_view(),name='category_view'),
    ]

video/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.utils.timezone import now
from django.contrib.auth.models import User,auth
from django.urls import reverse

# Create your models here.
class categorylist(models.Model):
    name= models.CharField(max_length=50,unique=True)
    img= models.ImageField(upload_to='categorylist',blank=True)
    slug=models.SlugField(unique=True)

    class  Meta:
        ordering=('name',)

    def __str__(self):
        return self.name


    
class Item(models.Model):
    sno=models.AutoField(primary_key=True)
    category=models.ForeignKey(categorylist, on_delete=models.CASCADE)
    slug=models.SlugField(unique=True)
    title=models.CharField(max_length=100)
    video=EmbedVideoField()


    desc=models.TextField()
    publish=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-title',)

    def __str__(self):
        return self.title
        


class VideoComment(models.Model):
    srno = models.AutoField(primary_key=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article= models.ForeignKey(Item, on_delete=models.CASCADE)    
    parent= models.ForeignKey('self', on_delete=models.CASCADE,null=True)
    timestamp= models.DateTimeField(default = now)
    def __str__(self):
        return self.comment[0:10] + "..." + self.user.username

video/views.py
from django.shortcuts import render
from .models import categorylist,Item,VideoComment
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.contrib import messages
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse


# Create your views here.
def category_list(request):
    print("invoked1")
    categories=categorylist.objects.all()
    return render(request,"video/categorylist.html",{ 'categories': categories })


# class categories(ListView):
#    model=categorylist
#    context_object_name='categories'
#    template_name='video/categorylist.html'

def category_view(request,category_slug):
    print("invoked2")
    category = categorylist.objects.filter(slug=category_slug).first()
    article=Item.objects.filter(category=category)
    return render(request,'video/categoryview.html',{'category':category,"article": article})

# class categoryviews(ListView):
#     template_name='video/categoryview.html'
#     context_object_name='article'

#     def get_queryset(self):
#         self.category=get_object_or_404(categorylist,slug=self.kwdargs['category_slug'])
#         return Item.objects.filter(category=self.category)

#     def get_context_data(self,**kwdargs):
#         context = super().get_context_data(**kwargs)
#         context["categoryview"] = self.category
#         return context
        
# class ArticleDetail(DetailView):
#     slug_url_kwarg='article_slug'
#     model=Item
#     template_name='video/articledetail.html'
#     context_object_name='article'

def article_detail(request,article_slug):
    article=Item.objects.filter(slug=article_slug).first()
    comments=VideoComment.objects.filter(article=article,parent=None)
    replies=VideoComment.objects.filter(article=article).exclude(parent=None)
    repDict={}
    for reply in replies:
        if reply.parent.srno not in repDict.keys():
            repDict[reply.parent.srno]=[reply]
        else:
            repDict[reply.parent.srno].append(reply)

    context={'article':article,'comments':comments,'user':request.user,'repDict':repDict}
    print("Now i m called")

    return render(request,'video/article_detail.html', context)


def postComment(request):
    print("hi")
    if request.method=="POST":
        print("hello")
        comment=request.POST.get("comment")
        user=request.user
        articleSno=request.POST.get("articleSno")
        article=Item.objects.get(sno=articleSno)
        parentSno=request.POST.get("parentSno")
        print("response")
        if parentSno=="":
            comment=VideoComment(comment=comment,user=user,article=article)
            print("hello again")
            comment.save()
            messages.success(request,"Your comment has been posted successfully")
        else:
            parent=VideoComment.objects.get(srno=parentSno)
            comment=VideoComment(comment=comment,user=user,article=article,parent=parent)

            comment.save()
            messages.success(request,"Your reply has been posted successfully")
        return HttpResponseRedirect(reverse('video:article_detail',args=(article.slug,)))

templates/video/ardyl.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}
{% load humanize%}
{% comment %} {% load extras %} {% endcomment %} 
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h2> How to install {{article.title}} </h2>
            <div class="container embed-responsive embed-responsive-16by9 px-3" id="vid">
                {% video article.video 'small' %}
            </div>
            <p>{{article.desc|safe}}</p>
        </div>
    </div>

<div class="container"> 
            <h2>{{comments.count}} Comments</h2>
            <div class="my-3">
                {% if user.is_authenticated %}
                <form action="/video/postComment" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Write your comment</label>
                        <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                        <input type="hidden" name="parentSno" value="">
    
                    </div>
                <input type="hidden" name="articleSno" value="{{article.sno}}">
                <input type="submit" value="Submit">
                </form>
                {% else %}
                      <div class="card card-body">
                          <div class="row">
                              <div class="col-md-6">
                                <h3>Please <a href="{% url 'users:login' %}?next={% firstof request.path '/' %}">Login</a>to comment or reply</h3>
                              </div>
                              <div class="col-md-6">

                                    <h3 style="margin-top: 10px;font-weight:bold;">Don't Have Account?</h3>
                                    <button style="margin-left: 8px; padding:3px 5px;"><a href="{% url 'users:register' %}?next={% firstof request.path '/' %}" style="text-decoration: none;">Create an Account</a></button>
                            
                              </div>
                          </div>
                      
               
        </div>
                {% endif %}
            </div>
</div>
{% for comment in comments %}
            <div class="row my-3">
                
                <div class="col-md-1"><img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"></div>
                <div class="col-md-11"><b>{{comment.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{comment.timestamp|naturaltime}}</span></div>
                <div>{{comment.comment}}</div>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.srno}}">
                        <div class="card card-body my-2">
                            <form action="/videos/postComment" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Post a reply</label>
                                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                                <input type="hidden" name="parentSno" value="{{comment.srno}}">
                
                                </div>
                            <input type="hidden" name="articleSno" value="{{article.sno}}">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}" disabled>
                       Reply
                    </button>
                    {% endif %}
                    <div class="replies my-2">
                        {% for reply in repDict|get_val:comment.srno %}
                        <div class="row">
                            <div class="col-md-1">
                                <img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"> 
                            </div>
                            <div class="col-md-11">
                                <b>{{reply.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{reply.timestamp|naturaltime}}</span>
                                <div>{{reply.comment}}</div>

                        </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock content%}

templates/video/article_detail.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %}
{% load humanize%}
{% load extras %} 
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h2> How to install {{article.title}} </h2>
            <div class="container embed-responsive embed-responsive-16by9 px-3" id="vid">
                {% video article.video 'small' %}
            </div>
            <p>{{article.desc|safe}}</p>
        </div>
    </div>

<div class="container"> 
            <h2>{{comments.count}} Comments</h2>
            <div class="my-3">
                {% if user.is_authenticated %}
                <form action="/videos/postComment" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Write your comment</label>
                        <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                        <input type="hidden" name="parentSno" value="">
    
                    </div>
                <input type="hidden" name="articleSno" value="{{article.sno}}">
                <input type="submit" value="Submit">
                </form>
                {% else %}
                      <div class="card card-body">
                          <div class="row">
                              <div class="col-md-6">
                                <h3>Please <a href="{% url 'users:login' %}?next={% firstof request.path '/' %}">Login</a>to comment or reply</h3>
                              </div>
                              <div class="col-md-6">

                                    <h3 style="margin-top: 10px;font-weight:bold;">Don't Have Account?</h3>
                                    <button style="margin-left: 8px; padding:3px 5px;"><a href="{% url 'users:register' %}?next={% firstof request.path '/' %}" style="text-decoration: none;">Create an Account</a></button>
                            
                              </div>
                          </div>
                      
               
        </div>
                {% endif %}
            </div>
</div>
{% for comment in comments %}
            <div class="row my-3">
                
                <div class="col-md-1"><img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"></div>
                <div class="col-md-11"><b>{{comment.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{comment.timestamp|naturaltime}}</span></div>
                <div>{{comment.comment}}</div>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}

                        <div class="card card-body my-2">
                            <form action="/videos/postComment" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Post a reply</label>
                                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                                <input type="hidden" name="parentSno" value="{{comment.srno}}">
                
                                </div>
                            <input type="hidden" name="articleSno" value="{{article.sno}}">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>

                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}" disabled>
                       Reply
                    </button>
                    {% endif %}
                    <div class="replies my-2">
                        {% for reply in repDict|get_val:comment.srno %}
                        <div class="row">
                            <div class="col-md-1">
                                <img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"> 
                            </div>
                            <div class="col-md-11">
                                <b>{{reply.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{reply.timestamp|naturaltime}}</span>
                                <div>{{reply.comment}}</div>

                        </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div> 
{% endblock content%} 

templates/video/categorylist.html
{% extends 'base.html' %}
{% load static %}
{% block title  %} about us {% endblock title %}
{% block mycss %}
    <style>
    img{ 
        height:200px;
        width:200px;
    }
    </style>
{% endblock mycss %}
{% block content %}
<div class ="container">
    <div class="row">
    {% for c in categories %}
    <div class = "col_lg col_3">
    <h5><a href="{% url 'video:category_view' c.slug %}">{{c.name}}</a></h5>
    <img src="{{c.img.url}}"alt="img">
    </div>
    {% endfor %}
</div>
        {% endblock content %}

templates/video/categoryview.html
{% extends 'base.html' %}
{% load static %}
{% block title  %} about us {% endblock title %}
{% block content %}
<div class ="container">
    <div class="row">
         <h2>{{categoryview.name}}</h2>
         {% for ar in article %}
         <div class = "col col-md-3"
             <h3>{{ar.title}}</h3>>
             <img src="{{ar.img.url}}" alt="modimage">
            <h4><a href="{% url 'video:article_detail' ar.slug %}">
            show me details</a></h4>
         {% endfor %} 
        </div>
    </div>
</div>
        {% endblock content %}