blog1/urls.py
from django.urls import path,include
from blog1 import views

app_name='blog1'
urlpatterns=[
    path('',views.blog1Home,name='blog1Home'),
    path('<int:pk>',views.blog1Post,name="blog1Post"),


]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('videos/',include(('video.urls','video'),namespace='video')),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('blog1/',include(('blog1.urls','blog1'),namespace='blog1')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
from django.views.generic import TemplateView

app_name='home'

urlpatterns=[
    path('',views.home, name='home'),
    path("about/",views.about,name='about'),
    path("search/",views.search,name='search'),
]

users/urls.py
from django.urls import path
from users import views




app_name='users'
urlpatterns=[
    path('register',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

video/urls.py
from django.urls import path
from video import views
# from video.views import categories,categoryviews,article_detail


app_name='video'
urlpatterns=[
    path('categorylist/',views.category_list,name='category'),
    path('<slug:category_slug>/',views.category_view,name='category_view'),
    path('postComment',views.postComment, name='postComment'),
    path('<slug:article_slug>',views.article_detail, name='article_detail'),
    #path('slug:category_slug>/',ArticleDetail.as_view(),name='article_detail'),
    #path('slug:category_slug>/',categoryviews.as_view(),name='category_view'),
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %} {% endblock title %} </title>
{% block mycss %}{% endblock mycss %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Mate+SC&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href ="{% static 'css/style.css' %}" rel ="stylesheet" type= "text/css" >

</head>
<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'home:about' %}">About </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog1:blog1Home' %}">Blog </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'video:category' %}">Video</a>
        </li>
  
      
      <form class="d-flex" method='GET' action='/search'>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li clas="nav-item">Hi,{{user.first_name}}</li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% block loginactive %}{%endblock loginactive %}">
        <a class="nav-link" href="{%  url 'users:login' %}">Login</a>
        </li>
        <!-- Button to trigger signup modal-->
        <li class="nav-item {% block signupactive %} {% endblock signupactive %}">
          <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
</nav>

{% for message in messages %}
<div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
  <strong>New Message:</strong>{{ message }}
  <button type="button" class="clase" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}

{% block content %}
{% endblock content %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>


</body>
</html>